### ISSUE TITLE
Angular 14 support

### ISSUE THREAD

**Issue by vvasiloud** [avivharuzi/ngx-seo#3]
Hello,

Any plans to support Angular 14.x.x?

`
npm ERR! While resolving: @avivharuzi/ngx-seo@13.0.1
npm ERR! Found: @angular/common@14.0.6
npm ERR! node_modules/@angular/common
npm ERR!   @angular/common@"~14.0.0" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/common@"13.x" from @avivharuzi/ngx-seo@13.0.1
npm ERR! node_modules/@avivharuzi/ngx-seo
npm ERR!   @avivharuzi/ngx-seo@"^13.0.1" from the root project
`

Thanks!

**Comment by avivharuzi** [comment]
Updated to version 14 to support Angular 14
